image:
  repository: gcr.io/cloud-solutions-images/janusgraph
  tag: v2
  pullPolicy: IfNotPresent

minReplicas: 2
maxReplicas: 64

resources: {}

service:
  type: ClusterIP
  port: 8182

elasticsearch:
  rbac:
    create: true

cassandra:
  config:
    max_heap_size: 1024M
  resources:
    requests:
      cpu: 0.5
      memory: 2Gi
