image:
  repository: gcr.io/cloud-solutions-images/janusgraph
  tag: v2
  pullPolicy: IfNotPresent

replicas: 1

resources: {}

service:
  type: ClusterIP
  port: 8182

elasticsearch:
  rbac:
    create: true

cassandra:
  resources:
    requests:
      cpu: 0.5
      memory: 2Gi
